cart/urls.py
from django.urls import path
from .views import CartView, AddCartView, CheckoutView, RemoveCartView, RemoveCartItemView

urlpatterns = [
    path('', CartView.as_view(), name="cart_view"),
    path('add_cart/<int:product_id>/', AddCartView.as_view(), name="add_cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', RemoveCartView.as_view(), name="remove_cart"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', RemoveCartItemView.as_view(), name="remove_cart_item"),

    path('checkout/', CheckoutView.as_view(), name="checkout_view"),
]

greatkart/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', include('thesite.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import ReviewsView, SearchView, StoreView, ProductDetailView

urlpatterns = [
    path('', StoreView.as_view(), name="store"),
    path('category/<slug:category_slug>/', StoreView.as_view(), name="products_by_cats"),
    path('category/<slug:category_slug>/<slug:product_slug>/', ProductDetailView.as_view(), name="products_detail"),
    path('search/', SearchView.as_view(), name="search"),
    path('reviews/<int:product_id>/', ReviewsView.as_view(), name="reviews"),
]

thesite/urls.py
from django.urls import path
from .views import SiteBaseView

urlpatterns = [
    path('', SiteBaseView.as_view(), name="site-index-view"),
]

cart/models.py
from django.db import models
from store.models import Product, ProductVariation
from extras.models import BaseModel
from accounts.models import Account

# Create your models here.
class Cart(BaseModel):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = "tbl_cart"
        verbose_name = 'cart'
        verbose_name_plural = 'carts'

    def __str__(self):
        return self.cart_id

class ItemInCart(BaseModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(ProductVariation, blank=True)
    cart    = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    user    = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()

    class Meta:
        db_table = "tbl_item_in_cart"
        verbose_name = 'item_in_cart'
        verbose_name_plural = 'item_in_carts'

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

store/models.py
from django.db import models
from django.urls import reverse
from accounts.models import Account
from category.models import Category
from extras.models import BaseModel
from django.utils.html import mark_safe
from django.db.models import Avg, Count

VARIATION_CATEGORY = [
    ('color', 'color'),
    ('size', 'size')
]

# Create your models here.
class Product(BaseModel):
    product_name    = models.CharField(max_length=200, unique=True)
    slug            = models.SlugField(max_length=200, unique=True)
    description     = models.TextField(max_length=500, blank=True)
    price           = models.IntegerField()
    images          = models.ImageField(upload_to='photos/products')
    stock           = models.IntegerField()
    is_available    = models.BooleanField(default=True)
    category        = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        db_table = "tbl_products"
        verbose_name = 'product'
        verbose_name_plural = 'products'
    
    def __str__(self):
        return self.product_name

    def get_url(self):
        return reverse('products_detail', args=[self.category.slug, self.slug])
    
    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

    def image_tag(self):
        if self.images:
            return mark_safe('<img src="%s" width="70" height="70" />' % (self.images.url,))

    image_tag.short_description = 'Product Images'
    image_tag.allow_tags = True


class VariationManager(models.Manager):

    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)
    
    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


class ProductVariation(BaseModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=255, choices=VARIATION_CATEGORY)
    variation_value = models.CharField(max_length=255)

    objects = VariationManager()

    class Meta:
        db_table = "tbl_product_variation"
        verbose_name = 'product__variation'
        verbose_name_plural = 'product_variations'

    def __str__(self):
        if self.product:
            return self.product.product_name+":"+self.variation_value
        else:
            return 'Default Variant'


class ReviewRating(BaseModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)

    class Meta:
        db_table = "tbl_review_rating"
        verbose_name = 'review_rating'
        verbose_name_plural = 'review_ratings'

    def __str__(self):
        if self.product:
            return f"{self.product.product_name} - {self.rating} - {self.subject}"
        else:
            return 'No Rating'


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    class Meta:
        db_table = "tbl_product_gallery"
        verbose_name = 'product_gallery'
        verbose_name_plural = 'product_galleries'

    def __str__(self):
        if self.product:
            return self.product.product_name
        return 'No Product'
    
    def image_tag(self):
        if self.image:
            return mark_safe('<img src="%s" width="70" height="70" />' % (self.image.url,))

    image_tag.short_description = 'Product Images'
    image_tag.allow_tags = True

thesite/models.py
from django.db import models

# Create your models here.

store/forms.py
from django import forms
from .models import ReviewRating

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

cart/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from store.models import Product, ProductVariation
from .models import Cart, ItemInCart
from extras.utility import UtilityManager
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.
class CartView(View):

    def get(self, request, total=0, quantity=0, *args, **kwargs):
        context = {}
        tax = 0
        grand_total = 0
        the_cart_items = None

        the_utility = UtilityManager(request)

        try:
            if request.user.is_authenticated:
                the_cart_items = ItemInCart.objects.filter(user=request.user, is_active=True)
            else:
                the_cart = Cart.objects.get(cart_id=the_utility.get_or_create_session())
                the_cart_items = ItemInCart.objects.filter(cart=the_cart, is_active=True)
            for cart_item in the_cart_items:
                total += (cart_item.product.price * cart_item.quantity)
                quantity += cart_item.quantity
            tax = (2 * total)/100
            grand_total = total + tax
        except ObjectDoesNotExist:
            pass
        
        context = {
            'total': total,
            'quantity': quantity,
            'cart_items': the_cart_items,
            'tax': tax,
            'grand_total': grand_total,
        }
        return render(request, 'thesite/cart.html', context)

class AddCartView(View):

    def post(self, request, product_id, *args, **kwargs):
        current_user = request.user
        the_product = Product.objects.get(id=product_id)
        the_utility = UtilityManager(request)
        if current_user.is_authenticated:
            product_variations = []

            for key, value in request.POST.items():
                try:
                    the_variation = ProductVariation.objects.get(product=the_product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variations.append(the_variation)
                except ProductVariation.DoesNotExist:
                    pass

            is_cart_item_exists = ItemInCart.objects.filter(product=the_product, user=current_user).exists()
            if is_cart_item_exists:
                the_item_cart = ItemInCart.objects.filter(product=the_product, user=current_user)
                existing_variation_list = []
                ids = []
                for item in the_item_cart:
                    existing_variation = item.variations.all()
                    existing_variation_list.append(list(existing_variation))
                    ids.append(item.id)

                if product_variations in existing_variation_list:
                    index = existing_variation_list.index(product_variations)
                    item_id = ids[index]
                    item_in_cart = ItemInCart.objects.get(product=the_product, id=item_id)
                    item_in_cart.quantity += 1
                    item_in_cart.save()
                else: 
                    itemcartobj = ItemInCart.objects.create(product=the_product, quantity = 1, user = current_user, is_active = True)
                    if len(product_variations) > 0:
                        itemcartobj.variations.clear()
                        itemcartobj.variations.add(*product_variations)
                    itemcartobj.save()
            else:
                the_item_cart = ItemInCart()
                the_item_cart.product = the_product
                the_item_cart.user = current_user
                the_item_cart.quantity = 1
                the_item_cart.is_active = True
                the_item_cart.save()
                
                if len(product_variations) > 0:
                    the_item_cart.variations.clear()
                    the_item_cart.variations.add(*product_variations)
                    the_item_cart.save()

            return redirect('cart_view')
        else:
            product_variations = []

            for key, value in request.POST.items():
                try:
                    the_variation = ProductVariation.objects.get(product=the_product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variations.append(the_variation)
                except ProductVariation.DoesNotExist:
                    pass

            try:
                the_cart = Cart.objects.get(cart_id=the_utility.get_or_create_session())
                the_cart.save() #if cart is already exists
            except Cart.DoesNotExist:
                the_cart = Cart()
                the_cart.cart_id = the_utility.get_or_create_session()
                the_cart.save()


            is_cart_item_exists = ItemInCart.objects.filter(product=the_product, cart=the_cart).exists()
            if is_cart_item_exists:
                the_item_cart = ItemInCart.objects.filter(product=the_product, cart=the_cart)
                existing_variation_list = []
                ids = []
                for item in the_item_cart:
                    existing_variation = item.variations.all()
                    existing_variation_list.append(list(existing_variation))
                    ids.append(item.id)

                print("existing_variation_list---", existing_variation_list)

                if product_variations in existing_variation_list:
                    index = existing_variation_list.index(product_variations)
                    item_id = ids[index]
                    item_in_cart = ItemInCart.objects.get(product=the_product, id=item_id)
                    item_in_cart.quantity += 1
                    item_in_cart.save()
                else: 
                    itemcartobj = ItemInCart.objects.create(product=the_product, quantity = 1, cart = the_cart, is_active = True)
                    if len(product_variations) > 0:
                        itemcartobj.variations.clear()
                        itemcartobj.variations.add(*product_variations)
                    itemcartobj.save()
            else:
                the_item_cart = ItemInCart()
                the_item_cart.product = the_product
                the_item_cart.cart = the_cart
                the_item_cart.quantity = 1
                the_item_cart.is_active = True
                the_item_cart.save()
                
                if len(product_variations) > 0:
                    the_item_cart.variations.clear()
                    the_item_cart.variations.add(*product_variations)
                    the_item_cart.save()

            return redirect('cart_view')

class RemoveCartView(View):

    def get(self, request, product_id, cart_item_id, *args, **kwargs):
        product = get_object_or_404(Product, id=product_id)
        try:
            if request.user.is_authenticated:
                the_cart_item = ItemInCart.objects.get(product=product, user=request.user, id=cart_item_id)
            else:
                the_utility = UtilityManager(request)
                the_cart = Cart.objects.get(cart_id=the_utility.get_or_create_session())
                the_cart_item = ItemInCart.objects.get(product=product, cart=the_cart, id=cart_item_id)
            if the_cart_item.quantity > 1:
                the_cart_item.quantity -= 1
                the_cart_item.save()
            else:
                the_cart_item.delete()
        except:
            pass
        return redirect('cart_view')

class RemoveCartItemView(View):

    def get(self, request, product_id, cart_item_id, *args, **kwargs):
        product = get_object_or_404(Product, id=product_id)
        if request.user.is_authenticated:
            the_cart_item = ItemInCart.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            the_utility = UtilityManager(request)
            the_cart = Cart.objects.get(cart_id=the_utility.get_or_create_session())
            the_cart_item = ItemInCart.objects.get(product=product, cart=the_cart, id=cart_item_id)
        
        the_cart_item.delete()
        return redirect('cart_view')


class CheckoutView(View):

    @method_decorator(login_required(login_url='/accounts/login/'))
    def get(self, request, total=0, quantity=0, *args, **kwargs):
        context = {}
        tax = 0
        grand_total = 0
        the_cart_items = None

        the_utility = UtilityManager(request)

        try:
            if request.user.is_authenticated:
                the_cart_items = ItemInCart.objects.filter(user=request.user, is_active=True)
            else:
                the_cart = Cart.objects.get(cart_id=the_utility.get_or_create_session())
                the_cart_items = ItemInCart.objects.filter(cart=the_cart, is_active=True)
            for cart_item in the_cart_items:
                total += (cart_item.product.price * cart_item.quantity)
                quantity += cart_item.quantity
            tax = (2 * total)/100
            grand_total = total + tax
        except ObjectDoesNotExist:
            pass
        
        context = {
            'total': total,
            'quantity': quantity,
            'cart_items': the_cart_items,
            'tax': tax,
            'grand_total': grand_total,
        }
        return render(request, 'thesite/checkout.html', context)

thesite/views.py
from django.shortcuts import render
from django.views import View
from store.models import Product, ReviewRating

# Create your views here.
class SiteBaseView(View):

    def get(self, request, *args, **kwargs):
        context = {}

        products = Product.objects.filter(is_available=True)

        # Get the reviews
        reviews = None
        for product in products:
            reviews = ReviewRating.objects.filter(product_id=product.id, status=True)


        context = {
            'products': products,
            'reviews': reviews,
        }
        return render(request, 'thesite/index.html', context)

thesite/templates/thesite/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    {% include 'includes/alert.html' %}
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-9">
                <article class="card">
                    <header class="card-header">
                        <strong class="d-inline-block mr-3">Logged in as:</strong>
                        <span>{{user.full_name}}</span>
                    </header>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="card" style="text-align:center;">
                                    <div class="card-body">
                                        <h5 class="card-title">Total Orders</h5>
                                        <h4>{{orders_count}}</h4>
                                        <a href="{% url 'my_orders' %}">View Orders</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card" style="text-align:center;">
                                    <div class="card-body">
                                        {% if userprofile.profile_picture %}
                                        <img src="{{userprofile.profile_picture.url}}" alt="User Profile Picture" width="50" height="50" style="border-radius:50%;">
                                        {% else %}
                                        <img src="{% static './images/avatars/avatar1.jpg' %}" alt="User Profile Picture" width="50" height="50" style="border-radius:50%;">
                                        {% endif %}
                                        <p class="mb-0">{{user.email}}</p>
                                        <p>{{user.phone}}</p>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- row.// -->
                    </div> <!-- card-body .// -->
                    
                </article> <!-- order-group.// -->
            </main>
        </div> <!-- row.// -->
    </div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

thesite/templates/thesite/myorder.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    {% include 'includes/alert.html' %}
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-9">
                <article class="card">
                <header class="card-header">
                    <strong class="d-inline-block mr-3">Your order history</strong>
        
                </header>
                <div class="card-body">
                    <div class="row">
                    <div class="col-md-12">
                        <table class="table table-hover">
                          <thead>
                            <tr>
                              <th scope="col">Order #</th>
                              <th scope="col">Billing Name</th>
                              <th scope="col">Phone</th>
                              <th scope="col">Order Total</th>
                                    <th scope="col">Date</th>
                            </tr>
                          </thead>
                          <tbody>
                                {% for order in orders %}
                            <tr>
                              <th scope="row"><a href="{% url 'order_detail' order.order_number %}">{{order.order_number}}</a></th>
                              <td>{{order.full_name}}</td>
                              <td>{{order.phone}}</td>
                              <td>${{order.order_total}}</td>
                                    <td>{{order.created_at}}</td>
                            </tr>
                        {% endfor %}
        
                          </tbody>
                        </table>
                    </div>
        
                    </div> <!-- row.// -->
                </div> <!-- card-body .// -->
        
                </article> <!-- order-group.// -->
            </main>
        </div> <!-- row.// -->
    </div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

thesite/templates/thesite/product_detail.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap mainImage">
              <center><img src="{{product.images.url}}" /></center>
            </div>
            <!-- img-big-wrap.// -->
          </article>
          <!-- gallery-wrap .end// -->
          <ul class="thumb">
						<li>
							<a href="{{ product.images.url }}" target="mainImage"><img src="{{ product.images.url }}" alt="Product Image"></a>
							{% for i in product_gallery %}
							<a href="{{i.image.url}}" target="mainImage"><img src="{{i.image.url}}" alt="Product Image"></a>
							{% endfor %}
						</li>
					</ul>
        </aside>
        <main class="col-md-6 border-left">
          <form action="{% url 'add_cart' product.id %}" method="POST">
            {% csrf_token %}
            <article class="content-body">
              <h2 class="title">{{product.product_name}}</h2>
              <div class="rating-star">
                <span>
                  <i class="fa fa-star{% if product.averageReview < 0.5 %}-o{% elif product.averageReview >= 0.5 and product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if product.averageReview < 1.5 %}-o{% elif product.averageReview >= 1.5 and product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if product.averageReview < 2.5 %}-o{% elif product.averageReview >= 2.5 and product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if product.averageReview < 3.5 %}-o{% elif product.averageReview >= 3.5 and product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if product.averageReview < 4.5 %}-o{% elif product.averageReview >= 4.5 and product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
                  <span>{{product.countReview}} reviews</span>
                  </span>
              </div>

              <div class="mb-3">
                <var class="price h4">$ {{product.price}}</var>
              </div>

              <p>
                {{product.description}}
              </p>

              <hr />
              <div class="row">
                <div class="item-option-select">
                  <h6>Choose Color</h6>
                  <select name="color" class="form-control" required>
                    <option value="" disabled selected>Select</options>
                    {% for i in product.productvariation_set.colors %}
                    <option value="{{i.variation_value}}">{{i.variation_value}}</options>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <div class="row">
                <div class="item-option-select">
                  <h6>Select Size</h6>
                  <select name="size" class="form-control">
                    <option value="" disabled selected>Select</options>
                    {% for i in product.productvariation_set.sizes %}
                    <option value="{{i.variation_value}}">{{i.variation_value}}</options>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <hr />
              {% if product.stock <= 0 %}
              <h5 class="text-danger">Out of stock</h5>
              {% else %}
                <button type="submit" class="btn btn-primary">
                  <span class="text">Add to cart</span>
                  <i class="fas fa-shopping-cart"></i>
                </button>
              {% endif %}
            </article>
          </form>
          <!-- product-info-aside .// -->
        </main>
        <!-- col.// -->
      </div>
      <!-- row.// -->
    </div>
    <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br />

    <div class="row">
      <div class="col-md-9">
        <form action="{% url 'reviews' product.id %}" method="post">
          {% csrf_token %}
          <h5>Write Your Reviews</h5>
          <div class="rate">
            <input type="radio" name="rating" id="rating10" value="5" required /><label for="rating10" title="5"></label>
							<input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5" class="half"></label>
							<input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8" title="4"></label>
							<input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5" class="half"></label>
							<input type="radio" name="rating" id="rating6" value="3" required /><label for="rating6" title="3"></label>
							<input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5" class="half"></label>
							<input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4" title="2"></label>
							<input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5" class="half"></label>
							<input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2" title="1"></label>
							<input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5" class="half"></label>
          </div>
          <br>
          Review Title:
          <input type="text" class="form-control" name="subject">
          <br>
          Review:
          <textarea name="review" rows="4" class="form-control"></textarea>
          <br>
          {% if user.is_authenticated %}
          <input type="submit" value="Submit Review" class="btn btn-primary mb-3">
          {% else %}
          <p>You must be logged in to post a review. <span><a href="{% url 'login_view' %}">Login now</a></span></p>
					{% endif %}
          {% include 'includes/alert.html' %}
        </form>

        <header class="section-heading">
          <h3>Customer Reviews</h3>
          <div class="rating-star">
            <span>
              <i class="fa fa-star{% if product.averageReview < 0.5 %}-o{% elif product.averageReview >= 0.5 and product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if product.averageReview < 1.5 %}-o{% elif product.averageReview >= 1.5 and product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if product.averageReview < 2.5 %}-o{% elif product.averageReview >= 2.5 and product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if product.averageReview < 3.5 %}-o{% elif product.averageReview >= 3.5 and product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if product.averageReview < 4.5 %}-o{% elif product.averageReview >= 4.5 and product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
              <span>{{product.countReview}} reviews</span>
              </span>
          </div>
        </header>

        {% for review in reviews %}
        <article class="box mb-3">
          <div class="icontext w-100">
            <img
              src="{% static './images/avatars/avatar1.jpg' %}"
              class="img-xs icon rounded-circle"
            />
            <div class="text">
              <span class="date text-muted float-md-right">{{review.updated_at}} </span>
              <h6 class="mb-1">{{review.user.full_name}}</h6>
              <div class="rating-star">
								<span>
									<i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
								</span>
							</div>
            </div>
          </div>
          <!-- icontext.// -->
          <div class="mt-3">
            <h6>{{review.subject}}</h6>
            <p>
              {{review.review}}
            </p>
          </div>
        </article>
        {% endfor %}
      </div>
      <!-- col.// -->
    </div>
    <!-- row.// -->
  </div>
  <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

{% block customjs %}
<script>
  $(document).ready(function(){
		$('.thumb a').click(function(e){
			e.preventDefault();
			$('.mainImage img').attr('src', $(this).attr("href"));
		})
	})
</script>
{% endblock %}